### ISSUE TITLE
control for scrolling innertia

### ISSUE THREAD

**Issue by antonkulaga** [mirukana/mirage#102]
Scrolling speed and inertia in mirage are so high that it is very hard to read when scrolling. Please, decrease or make it configurable

**Comment by theotheroracle** [comment]
it is, might be just in the dev branch for now, but it is .

**Comment by theotheroracle** [comment]
as far as i know, it's at least toggleable ?

**Comment by mirukana** [comment]
This is now configurable in the dev branch, using the `kineticScrollingMaxSpeed` and `kineticScrollingDeceleration` values.
