### ISSUE TITLE
Naming conflict with Mirage image viewer (Linux Packaging)

### ISSUE THREAD

**Issue by dreua** [mirukana/mirage#103]
Searching my distribution's (Fedora) repository for mirage, it came up with an [image viewer](http://mirageiv.sourceforge.net/). This will cause problems when mirage should be packaged in distributions. 

Currently there seems to be only one linux package in Arch called `matrix-mirage`. Assuming that you don't want to rename the project to something more unique it would be a good idea to make an official statement how linux packages should be called to avoid further complication and confusion.

Repology gives a good overview of packages in distributions:

- https://repology.org/projects/?search=mirage (Search)
- https://repology.org/project/matrix-mirage/versions (The messenger)
- https://repology.org/project/mirage/versions (The image viewer)

**Comment by AngryPenguinPL** [comment]
Hi. 
I created an RPM package for OpenMandriva and thought what to name it as it conflicted with an existing mirage package. That's why I chose the name "matrix-mirage".

**Comment by mirukana** [comment]
There's a [mirage-im](https://github.com/NixOS/nixpkgs/pull/84150) package being made for Nix, I'm in favor of this since it's shorter and starts with the actual name for the program (good for tab completion, sorting, etc).

**Comment by dreua** [comment]
That is my point: To avoid confusion and make it as easy as possible for users and developers alike it should be the same name on all or as many as distros as possible. Therefore an official statement by the developers in a place where packagers are likely to see it would be very helpful imo.

**Comment by besmily** [comment]
hi, what is the possible integrate web htpps?

**Comment by besmily** [comment]
ya t'il une version PHP?

**Comment by mirukana** [comment]
@besmily Please [open a new issue](https://github.com/mirukana/mirage/issues/new/choose) for your question, be as descriptive as possible / Ouvre une [nouvelle issue](https://github.com/mirukana/mirage/issues/new/choose) pour ta question, sois aussi descriptif que possible.

**Comment by mirukana** [comment]
There's now an official statement in the [CONTRIBUTING.md](https://github.com/mirukana/mirage/blob/master/docs/CONTRIBUTING.md#packaging).

**Comment by dreua** [comment]
Thanks! Just in case you didn't know: You as owner and everyone with some repo access can hide off topic comments like those from @besmily . (Three dot menu of the comment.) I do this whenever I can to keep things clean.
