### ISSUE TITLE
Impossible to select text entry fields on touchscreen

### ISSUE THREAD

**Issue by rinigus** [mirukana/mirage#115]
### Description

On touchscreen, I cannot select text input areas. Area gets automatically focused for text entry on opening Mirage, but after loosing focus during interaction, you cannot select any. This is major obstacle if you need to login for example - there is no way I can enter password. Same problem is frequent in the chat view as well.

### Your environment

- OS or distribution: Sailfish
- Architecture armh7l
- How did you install Mirage: flatpak

**Comment by mirukana** [comment]
Does https://github.com/mirukana/mirage/commit/71a2951f5bca0bc5bbe979195b8f44f7bfbc7b24 and https://github.com/mirukana/mirage/commit/7502c1a9b4e58171da1728863b33e86aff35db65 fix this?

**Comment by rinigus** [comment]
Yes, it is fixed now. Thank you!
