### ISSUE TITLE
Sort channel list alphabetically or force positions

### ISSUE THREAD

**Issue by pvonmoradi** [mirukana/mirage#119]
Currently the channel positioning gets swapped whenever a message is sent in them (in a distracting animated fashion). Is there a config to set it fixed?

**Comment by mirukana** [comment]
Will try to add alphabetic sorting before the next release.

**Comment by mirukana** [comment]
Added in dev branch commit a1b9f34958d5ea9847a5314a6b54bf7cdd5c9319.
Note that currently, you need to restart Mirage for the setting to apply.
