### ISSUE TITLE
Mirage does not gracefully handle having the session deleted from underneath it

### ISSUE THREAD

**Issue by Cadair** [mirukana/mirage#121]
### Description

If mirage restores a session and the access token is no longer valid things do not go well.

### Steps to reproduce

Login to mirage, close the app, delete the session using element or similar, reopen mirage.

### Expected behavior

A popup box telling you that you have been logged out, and prompting you to reauth or similar

### Actual behavior

You are presented with an unending error message box.

**Comment by mirukana** [comment]
Will fix this before next release. Until then, you can remove the bad account from the *accounts.json* config file to get rid of the errors and relogin later.

**Comment by Cadair** [comment]
yeah that's what I did. Thanks.

**Comment by mirukana** [comment]
Fixed in dev branch.
