### ISSUE TITLE
Windows version for visually impaired people.

### ISSUE THREAD

**Issue by discapacidad5** [mirukana/mirage#128]
This version of the matrix program that can be operated by keyboard is suitable for people with visual disabilities who do not use a mouse but do everything through the keyboard It would be good if there could be a version for Windows desktop

**Comment by mirukana** [comment]
Open issue for Windows and OSX support: https://github.com/mirukana/mirage/issues/24
Some work has been done to get us closer to a Windows port according to [this comment](https://github.com/mirukana/mirage/issues/24#issuecomment-658452627), I will see if I can resolve the situation with the mentioned pyotherside problem that has been blocking progress.
