### ISSUE TITLE
background image contains non-free embedded ICC profile

### ISSUE THREAD

**Issue by jonassmedegaard** [mirukana/mirage#129]
The file <src/images/midnight.jpg> contains an embedded ICC profile, authored by Hewlett Packard with no licensing - i.e. that code is copyright-protected and not licensed for free redistribution or reuse.

The ICC profile represents the color space sRGB which is the default colorspace for web rendering, and is therefore superfluous.

Please strip the ICC profile from that image.

If curious (as others have been when I filed similar reports), the way I detect such issues is with the command-line tool `exiftool` part of the Perl library Image::ExifTool, available in Debian-based distributions in package libimage-exiftool-perl.

**Comment by mirukana** [comment]
Thanks, the metadata have been stripped in https://github.com/mirukana/mirage/commit/17a8e1ce1ef5f7cab89c9331d7755a29c1112a01.
