### ISSUE TITLE
source lacks copyright information

### ISSUE THREAD

**Issue by jonassmedegaard** [mirukana/mirage#134]
source files generally include SPDX license hint.  Great!

...but licensing has value only when granted by copyright holders.
Therefore it is commonly recommended to state *both* who holds copyright *and* which licensing they grant.

Legally neither copyright nor licensing is required: They are listed as a courtesy to users, to ease _their_ potential legal need for verifying such information, where it is crucial to know _who_ to ask if the stated licensing is correct.

Please add copyright statement, ideally as one or more lines _above_ the SPDX license statement, in all copyright protected files.

**Comment by mirukana** [comment]
Fixed in https://github.com/mirukana/mirage/commit/4dc5c9a50d2ddfbace55633afb52dabe55e8ba5f.
