### ISSUE TITLE
Add Gentoo package

### ISSUE THREAD

**Issue by TheEvilSkeleton** [mirukana/mirage#135]
Hello, we have created a Gentoo package in our overlay. If you want, I can submit a PR to include our builds.

https://gitlab.com/src_prepare/src_prepare-overlay/-/tree/master/net-im/mirage

**Comment by mirukana** [comment]
PR would be welcome, thanks. 
I notice you include all the submodules in your build by the way, the only one currently used is hsluv-c and the others are just here to not break building older commits.
