### ISSUE TITLE
Mirage misinterprets HTTP 401 even on unauthenticated requests

### ISSUE THREAD

**Issue by LEdoian** [mirukana/mirage#147]
### Description

(As discussed today on #mirage:matrix.org:) When Mirage receives HTTP 401 without a good reason (e.g. `M_UNKNOWN`), it seems to fall back to assume that the used authentication token is not valid anymore. In such cases, Mirage issues a logout request, invalidating the token server-side.

This, however, seems to happen even on unauthenticated endpoints, like `/_matrix/client/r0/profile/@somebody:somewhere.tld`. In this particular case, 401 is not a valid status code, but Mirage should still be resistant to such bugs.

### Your environment

- Arch Linux, x86_64, Mirage 0.6.4  from AUR, Qt version 5.15.1, Python 3.8.5

### Steps to reproduce

1. Trigger [Synapse issue 8520](https://github.com/matrix-org/synapse/issues/8520)

### Expected behavior

Maybe a popup / console log to inform of the broken server?

### Actual behavior

Got logged out, the "You are logged out" popup has shown, Synapse has received logout request. Also, this was spammed in the console output:
```
! 16:17:18 | qrc:/src/gui/MainPane/RoomDelegate.qml:238: TypeError: Cannot read property 'connecting' of null 
! 16:17:18 | qrc:/src/gui/MainPane/RoomDelegate.qml:214: TypeError: Cannot read property 'connecting' of null
 ! 16:17:18 | qrc:/src/gui/MainPane/RoomDelegate.qml:40: TypeError: Cannot read property 'presence' of null
```

**Comment by mirukana** [comment]
Fixed in 68213e90557a377343ad9423f603a0667cff17f3
