### ISSUE TITLE
Drag and Drop to Send Files

### ISSUE THREAD

**Issue by Tynach** [mirukana/mirage#151]
It doesn't seem possible currently, which is a shame; I don't really want to save a screenshot (for example) to a file before I share it, and I tend to use my clipboard history for things I want to paste many times throughout the day/week (clipboard history survives reboots, logging out/in, etc. with how I have it set up), so I'd prefer not to clutter it up with images.

**Comment by mirukana** [comment]
6fbafdd677f56b74503cd741610b28e81c01ce6b adds support for dropping files, text and links in a chat. 
The behavior for dropping an image from an application will depend on that application though; for example file managers and WebKit/WebEngine browsers give us a local file to upload while Firefox doesn't differentiate between images and links and only gives an URL. This can be worked around once we have better support for downloading media within Mirage.
