### ISSUE TITLE
Option to not move a room on the list when navigating to it

### ISSUE THREAD

**Issue by BurnyBoi** [mirukana/mirage#152]
I noticed that any time I select an unread room on the room list, Mirage will move it down to another spot on the room list. This is especially annoying when trying to use the "go to previous/next room" keys because it means if I'm trying to go up/down through unread rooms, they keep getting shuffled around while I'm moving through them and it makes it so much harder to just quickly move through them in the order they appear.

I think this could be remedied just by changing the behavior around so that the room list doesn't move an unread room when it is selected. Instead, wait until AFTER I move away from that room before moving it down to the read rooms. Let me know your thoughts.

**Comment by mirukana** [comment]
I like the idea, that would indeed make navigation easier. Will think about how to implement it.

**Comment by BurnyBoi** [comment]
Another way of implementing it would be to enter a "no movement" mode when navigating with the keys, so that it waits until you've settled on a room and X number of seconds has passed before then shuffling them by activity again

**Comment by mirukana** [comment]
Implemented in v0.7.0
