### ISSUE TITLE
CPU usage >3% even when not doing anything

### ISSUE THREAD

**Issue by greenfoo** [mirukana/mirage#153]
Is this CPU usage expected or am I doing something wrong? Thanks.

**Comment by mirukana** [comment]
Which CPU are you using? I have less than 1% usage on an AMD FX-8300, but I can't speak for others.

Is it the Python backend, or the QML interface that's using resources? To find out:
- Press F1 to open the debug console, type `py.destroy()`, then check CPU usage
- Restart the application, press F1, type `window.contentItem.children[1].destroy()`, check the CPU usage

**Comment by greenfoo** [comment]
It lloks like it is the QML interface:
```
CPU usage when idle:

  - After restart ---------------------------------------------> ~3.0 %
  - After restart + py.destroy() ------------------------------> ~3.0 %  
  - After restart + window.contentItem.children[1].destroy() --> ~0.3 %  
```
I'm on a Ryzen 3500U CPU, running mirage from flatpak on Gnome.

By the way, even if I "make the mirage window" not visible, it still uses this ~3.0 % CPU (I don't know if this is the way Qt is supposed to work).
Is there something else I can look at?

Thanks again.

**Comment by pp3345** [comment]
I am having the same issue with about the same numbers as in https://github.com/mirukana/mirage/issues/153#issuecomment-720048812 on an Intel Core i7-8550U. Ideally, the application shouldn't incur any CPU usage at all while idling.

**Comment by greenfoo** [comment]
More details (in case they help):

1. When running from the command line, the following message is constantly being spammed to stdout (~ once per second)
```
Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":99.0".
Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":99.0".
Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":99.0".
Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":99.0".
```

2. This happens on both X11 and wayland

3. This happens both with the Flatpak and AppImage versions (haven't tested the AUR yet... too many dependencies :P)

**Comment by mirukana** [comment]
Can you try https://github.com/mirukana/mirage/commit/f874f247d4ac3df662c9bf62d130c7467a10f736 to see if this lowers the CPU usage? 

> Xlib:  extension "MIT-SCREEN-SAVER" missing on display ":99.0".

I suppose you're running the application under XWayland? In any case, this problem is unrelated, please open a new issue for it following the bug report template.

**Comment by greenfoo** [comment]
I just tested f874f24 and it completely fixes the CPU usage issue. Thanks!
