### ISSUE TITLE
On account screen copy and paste your user ID

### ISSUE THREAD

**Issue by Thorgrimson** [mirukana/mirage#156]
i try to mark my user ID with the mouse for copy and paste but it wont work. instead i moved the backround of the window.

**Comment by BurnyBoi** [comment]
Clicking the user ID here to copy it right to clipboard seems like it would make sense. I'd argue even clicking a username in the chat window should either do this or put a tag for them in the message composer, but that'd be a different enhancement.

**Comment by mirukana** [comment]
With the last commits in the dev branch, the user ID is now a selectable read-only field with an associated copy button. 
Note that if you need to copy user ID in the current version, you can always right click on your account in the room list and use the option there.
