### ISSUE TITLE
Don't include state events as notifications

### ISSUE THREAD

**Issue by BurnyBoi** [mirukana/mirage#162]
Currently, state events such as someone joining/leaving a room, kicks, bans, etc show as the "!" grey notification icon on a room; the same icon used for when there is a new message that doesn't directly ping you. For those in many rooms, this causes it to appear on so many rooms, that you can't tell which ones actually have messages, and which ones will just have "X left the room" when you open it.

It would be nice to not have these state events included for this type of icon.

**Comment by mirukana** [comment]
This is "fixed" by default in v0.7.0, unless the `RoomList.local_unread_markers` option is turned on.
