### ISSUE TITLE
add option to start in background (in tray only)

### ISSUE THREAD

**Issue by uha4** [mirukana/mirage#164]
It wold be great to have a option to start mirage in the background without opening a window.

This is handy, when starting mirage automatically at login via autostart. I want the client running in the background to sync and notify on new messages, but keep my desktop tidy at startup. 

A simple config option would do, but  a command line option would be better. 
A command line option could be added at the autostart entry. This way the window still shows up when starting from the menu or command line.

This also is the way it works with other messengers like Signal-desktop (--start-in-tray) or Telegram-desktop (--startintray)

**Comment by mirukana** [comment]
CLI option added in 257a4033e446af25b8e8113bc8c3f53b982de5a3
