### ISSUE TITLE
Matrix Error missing token

### ISSUE THREAD

**Issue by besendorf** [mirukana/mirage#17]
When logged in to an account the following warning shows up on stdout.
```
WARNING:root:On @besendorf:matrix.org client startup: MatrixError(http_code=401, m_code='M_MISSING_TOKEN')
```

**Comment by mirukana** [comment]
In your *<[config folder](https://github.com/mirukana/mirage#configuration--theming)>/accounts.json*, does your account have a `token`, or is it empty? If not empty, is the token still valid (i.e. you didn't disconnect the device from another client)? 

Mirage doesn't handle disconnected accounts well yet, but you can remove it from accounts.json manually

**Comment by besendorf** [comment]
I do have tokens for both accounts and didn't disconnect them from another client. I didnt verify the mirage device though

**Comment by mirukana** [comment]
- Does the warning only gets printed once, or is it repeated?
- Can the account be used as usual?
- Does this also happen for other accounts?

**Comment by besendorf** [comment]
Does the warning only gets printed once, or is it repeated?
-> It repeats multiple times per second
Can the account be used as usual?
- yes
Does this also happen for other accounts?
- I tried two accounts on two different homeservers

**Comment by lc-guy** [comment]
Getting this too. On arch linux. Same thing, no disconnects, but warning messages in console (and my "user" panel seems to refresh indefinitely?).

**Comment by mirukana** [comment]
Does this still happen on the [new release](https://github.com/mirukana/mirage/releases)? If yes, more details should be printed when this kind of error happens, can you post the full traceback?

**Comment by besendorf** [comment]
I still see this on the new release. Now the error is also shown in the GUI:
```

Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 353, in _start
    await self.sync_task
  File "/tmp/.mount_MirageYuGUd1/usr/lib/python3.8/site-packages/nio/client/async_client.py", line 1044, in sync_forever
    await self.run_response_callbacks([await response])
  File "/tmp/.mount_MirageYuGUd1/usr/lib/python3.8/asyncio/tasks.py", line 608, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/tmp/.mount_MirageYuGUd1/usr/lib/python3.8/site-packages/nio/client/async_client.py", line 910, in sync
    response = await self._send(
  File "qrc:/src/backend/matrix_client.py", line 213, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (401, 'M_UNKNOWN_TOKEN')

**Comment by mirukana** [comment]
The server responds with `M_UNKNOWN_TOKEN` instead of the `M_MISSING_TOKEN` in your first report this time. The device must have been deleted somehow, or something happened to the accounts file. What happens if you remove the account from Mirage (either right click on the account in the left pane and "Sign out" or remove it from `accounts.json` and restart) and sign in again?

**Comment by besendorf** [comment]
I removed my accounts.json file and re-added my accounts. Now the error is gone. Seems like the accounts.json file wasnt updated with the new parameters when upgrading from 0.4.2 to 0.5

**Comment by mirukana** [comment]
Good to hear. I'll reopen the issue if someone else (@lc-guy?) reports still having these problems after logging out and in again.

For the new keys, the already present accounts added before 0.5.0 don't get them automatically, but they're technically optional and things still work fine without, though that might change in the future.

**Comment by besendorf** [comment]
I see the error again, today:
```
WARNING:root:On @besendorf:matrix.org profile retrieval: Traceback (most recent call last):
  File "qrc:/src/backend/matrix_client.py", line 286, in on_profile_response
    resp = future.result()
  File "qrc:/src/backend/backend.py", line 240, in get_profile
    response = await client.get_profile(user_id)
  File "/tmp/.mount_MiragemT2Lav/usr/lib/python3.8/site-packages/nio/client/async_client.py", line 236, in wrapper
    return await func(self, *args, **kwargs)
  File "/tmp/.mount_MiragemT2Lav/usr/lib/python3.8/site-packages/nio/client/async_client.py", line 2505, in get_profile
    return await self._send(ProfileGetResponse, method, path,)
  File "qrc:/src/backend/matrix_client.py", line 213, in _send
    raise MatrixError.from_nio(response)
backend.errors.MatrixError: (401, 'M_MISSING_TOKEN')
