### ISSUE TITLE
Mirage randomly replies to wrong message

### ISSUE THREAD

**Issue by BurnyBoi** [mirukana/mirage#171]
I can't tell you how many times now I've gone to reply to a message, and rather than replying to the intended message, it replies to some other random message they've written in the room, which makes my reply make no sense and just causes so much confusion.

Please fix what causes replies to go to the wrong message. I'm losing my mind.

**Comment by mirukana** [comment]
This was fixed in c22cb58c0a2452c7a1aa695f09a68558488a499c. Note that the problem didn't affect replying via keyboard, if for some reason you can't use the dev branch.
