### ISSUE TITLE
settings.json is not being created.

### ISSUE THREAD

**Issue by Hacker1245** [mirukana/mirage#181]
### Description

There is no config file created in .config or in any other listed directories

### Your environment

- Manjaro Linux
- x86 64 bit
- KDE 5.20.5
- matrix-mirage-git from AUR

### Steps to reproduce

1. Install matrix-mirage-git from AUR
2. Check any of the listed config folders

### Expected behavior

Config file is created.

### Actual behavior

accounts.json creates normally, settings.json does not.

**Comment by mirukana** [comment]
This AUR package uses our dev branch, which has a different config format; please see the [corresponding documentation](https://github.com/mirukana/mirage/tree/dev/docs). A link to it has been added in the top-left settings menu since 7fad0cd909536d8da99a1aeae27ec21a01a5a0af.
