### ISSUE TITLE
Matrix room for mirage/mailing list?

### ISSUE THREAD

**Issue by artiblaster** [mirukana/mirage#182]
I'm interested in trying mirage, but as an amateur, i don't suspect i'd be able to work an alpha version. Do you have an element room? You could announce new releases there. Or a mailing list?

Maybe github has a subscribe feature, but i don't know where it is.

**Comment by mirukana** [comment]
We have a matrix room: [#mirage-client:matrix.org](https://matrix.to/#/%23mirage-client:matrix.org)
You can also click the "Watch" button on github in the top right, which allows you to be notified of new releases by mail.
