### ISSUE TITLE
Notifications in system tray

### ISSUE THREAD

**Issue by yennor** [mirukana/mirage#185]
I'm not sure if it is a bug or a missing feature (which in my opinion is absolutely necessary).
I'm using mirage in debian testing with kde plasma 5.20.5. Mirage version is: 0.6.4~dfsg+~hsluv1.0.0-4

When I get a new message the icon in the system tray  should tell me so somehow. Otherwise I have to poll mirage all the time myself to see if there are any new messages.

**Comment by mirukana** [comment]
Desktop notifications are implemented in the dev branch.
