### ISSUE TITLE
AttributeError when logging in

### ISSUE THREAD

**Issue by MRAAGH** [mirukana/mirage#193]
### Description
Hi, I loaded up Mirage for the first time and got this:
![](https://f.mazie.rocks/Screenshot_2021-03-11_22-52-43.png)
Then I clicked on "Empty Room" and got this:
![](https://f.mazie.rocks/Screenshot_2021-03-11_22-53-04.png)
Then I logged out and tried with my alt account which is in fewer rooms and everything worked perfectly. Great program btw!

### Your environment

- OS or distribution: Arch Linux
- Architecture: 64 bit
- For Linux users: Awesome wm v4.3
- How did you install Mirage? `yay -S matrix-mirage` (installed from AUR)

**Comment by mirukana** [comment]
The `AttributeError` should be fixed by https://github.com/mirukana/mirage/commit/d74f978508343ce02bed6b5c763df03d785f9bbb. 
The second error looks like either your server is misbehaving, or this room doesn't exist anymore. Can you do anything else in it like send a message?

**Comment by MRAAGH** [comment]
The errors no longer happen, I can only assume that the second error was caused by the first. Thank you, everything works perfectly now!
