### ISSUE TITLE
Unsupported image format when sent from Nheko

### ISSUE THREAD

**Issue by MRAAGH** [mirukana/mirage#197]
### Description
Image being sent in Nheko:
![](https://f.mazie.rocks/Screenshot_2021-03-20_16-48-02.png)
Image fails to display in Mirage:
![](https://f.mazie.rocks/Screenshot_2021-03-20_16-48-13.png)
Error:
```
! 17:42:53 | qrc:/src/gui/Pages/Chat/Timeline/EventImage.qml:8:1: QML EventImage: Error decoding: file:///home/maze/.cache/mirage/downloads/fairydust.space/image_SwVTAgtakpBsBtlvKLpAXjRF.jpg: Unsupported image format
```
This is the file referred to by the error:
https://f.mazie.rocks/image_SwVTAgtakpBsBtlvKLpAXjRF.jpg
This is the image file downloaded by Mirage. But it is not a valid image file.

Notes: 
- images sent from Element display properly in Mirage; 
- images sent by other users using Nheko also fail to display in Mirage but display in Element; 
- I have tried with png and jpg image and neither displayed in Mirage after being sent from Nheko.

### Steps to reproduce

1. Send any image in an encrypted room using the Nheko client
2. Look at the same room in the Mirage client
3. Notice that the image does not display
4. Look at the downloaded file and notice it is not a valid image file

### Your environment

- OS or distribution: Arch Linux
- Architecture: 64 bit
- desktop environment or window manager: Awesome wm v4.3
- How did you install Mirage? `yay -S matrix-mirage-git` (installed from AUR but from source)
- Qt version: 5.15.2
- Python version: 3.9.2

And I installed Nheko with: `yay -S nheko-git`
and Nheko version is `nheko 0.8.1-b31e74d9`

**Comment by mirukana** [comment]
The image I download from your link (tried both browser and wget) is corrupted and not identifiable by any command or client I have, can you reproduce this with images from any other site?

**Comment by MRAAGH** [comment]
Sorry, I was a bit vague there. What I meant is that [this](https://f.mazie.rocks/image_SwVTAgtakpBsBtlvKLpAXjRF.jpg) is the "image file" downloaded by Mirage and is invalid. Meanwhile the original image that I sent in Nheko is [this](https://f.mazie.rocks/image.jpg) and it is a valid image.
But this specific image is irrelevant, as the issue happens with any image I receive from Nheko users.

**Comment by MRAAGH** [comment]
This issue does not seem to be happening any more, either it was fixed in Mirage/nio or Nheko changed the format

**Comment by MRAAGH** [comment]
issue no longer occurs
