### ISSUE TITLE
Didn't recognize @ (at) as part of URL

### ISSUE THREAD

**Issue by MRAAGH** [mirukana/mirage#199]
### Description

It happened with this URL: https://ponies.im/@sorunome/105945612358833076

![](https://f.mazie.rocks/Screenshot_2021-03-24_17-10-26.png)

### Your environment
- OS or distribution: Arch Linux
- Architecture: 64 bit
- desktop environment or window manager: Awesome wm v4.3
- How did you install Mirage? `yay -S matrix-mirage-git` (installed from AUR but from source)
- Qt version: 5.15.2
- Python version: 3.9.2

### Steps to reproduce

1. Open the Element client
2. Send this message using Element: `https://f.mazie.rocks/@test.png`
3. Look at this message in Mirage

### Expected behavior

The link should include the `@` and the part after it

### Actual behavior

Only the first part of the URL is highlighted

**Comment by mirukana** [comment]
Fixed by 91652f9b89bc2f71bca0896028674a8aa221b238
