### ISSUE TITLE
Empty directory ~/qrc:/src/config/ created on startup

### ISSUE THREAD

**Issue by MRAAGH** [mirukana/mirage#201]
### Description

Whenever I open Mirage, it creates these empty directories in my home directory: `qrc:/src/config/`, but nothing is put in there while the program is running.

### Your environment

- OS or distribution: Arch Linux
- Architecture: 64 bit
- desktop environment or window manager: Awesome wm v4.3
- How did you install Mirage? `yay -S matrix-mirage-git` (installed from AUR but from source)
- Qt version: 5.15.2
- Python version: 3.9.2

### Steps to reproduce

1. Delete `~/qrc:`
2. Start Mirage
3. Notice that `~/qrc:` is created

### Expected behavior

I don't like when programs add stuff to my home directory, especially if it's not hidden

**Comment by mirukana** [comment]
Fixed by ba3e93e658eb8c536a0dd803c8cb5fabbb68fb8f
