### ISSUE TITLE
Configuration and welcome screen is blocking the user on a thin screen

### ISSUE THREAD

**Issue by Hyask** [mirukana/mirage#207]
### Description

When using mirage with a very thin window (e.g on a Pinephone in vertical mode), the first screen after the login blocks the user, because there is no way to quit this screen and reach the room list.

### Your environment

- OS: Debian testing on desktop and Manjaro on Pinephone
- Architecture: x86_64 on desktop, aarch64 on Pinephone
- DE: sway on desktop, Plasma mobile on Pinephone
- Manual build
- 5.15.2 on both
- Python 3.9.2 on both

### Steps to reproduce

- Open the `General | Notifications | Security` screen by either clicking your avatar at the top of the room list, or by just logging in a first time.
- Reduce the width of the window until the room list disappears.

### Expected behavior

There should be a way to reach the room list from this panel, even with a thin window.

### Actual behavior

The user is stuck in the configuration panel.

![2021-04-08-16_13_53](https://user-images.githubusercontent.com/7489759/114044372-7a03ac00-9887-11eb-8388-de903c99efae.png)

### Workaround

On the Pinephone, putting it in horizontal mode makes the room list appear, and it's possible to get out of the panel. On a desktop, simply widen the window.

**Comment by mirukana** [comment]
Fixed in 5be5e94e2af482a78498dcedaa40cd490946d7c9 and b7aa3ff018af3643f93c8cd18bb48a2820933b6b
