### ISSUE TITLE
mouse buttons for going to earlier page and later page

### ISSUE THREAD

**Issue by MRAAGH** [mirukana/mirage#208]
Would be convenient to have mouse button 4 and mouse button 5 navigate through the history of visited pages, like in browsers and some other gui applications.

Something like this:
```
    TapHandler {
        acceptedButtons: Qt.BackButton
        onTapped: moveThroughHistory(-1)
    }
```
But I wasn't able to get it working independently of mouse position.

**Comment by mirukana** [comment]
Added in https://github.com/mirukana/mirage/commit/bb68f3dfafedb4d2deeead4a24c772dfc4bab03a. This was a bit more complicated than expected, see the comments for info.
