### ISSUE TITLE
Black screen after starting Mirage

### ISSUE THREAD

**Issue by MRAAGH** [mirukana/mirage#210]
### Description

Thought I'd make a proper issue for this. It started in the comments of bb68f3dfafedb4d2deeead4a24c772dfc4bab03a which is the first commit after which this issue happens.

When I compile and start Mirage, I get the loading animation followed by a black screen. See [video](https://f.mazie.rocks/blackmirage.webm)

I got this error: `qrc:/src/gui/UI.qml:164:9: GlobalTapHandlers is not a type`

After removing `~/.cache/mirage/mirage/qmlcache`, the issue persists.

### Your environment

- Arch Linux 64-bit
- window manager: Awesome wm v4.3
- How did you install Mirage? manual build
- Qt 5.15.2
- Python 3.9.2

**Comment by mirukana** [comment]
- Does *src/gui/GlobalTapHandlers.qml* exists for you?
- What does `grep GlobalTapHandlers  build/resources.qrc` returns?
- Do `make clean && qmake && make`, check if the grep above's result has changed and if the mirage still fails to load
- If it still fails, try also `make clean && qmake CONFIG+=dev && make`

**Comment by MRAAGH** [comment]
My apologies, I forgot to run `qmake`, that's why this was missing. It works fine now.
