### ISSUE TITLE
Received URLs cut at colon (`:`)

### ISSUE THREAD

**Issue by s3lph** [mirukana/mirage#216]
### Description

When I receive (not when sending) a message with an URL containing a colon (`:`), only the part before the colon is clickable and the link's destination is also trucated at the colon. Colons are however valid in URL components, and should not delimit them. This is especially cumbersome with e.g. links to Mediawiki file uploads (e.g.https://commons.wikimedia.org/wiki/File:Diagramme_Matrix_en.svg)

![Expected vs wrong behavior](https://user-images.githubusercontent.com/5564491/115117847-cbefb480-9fa0-11eb-9f82-435416281726.png)

### Your environment

- Distribution: Arch Linux
- Architecture: x86_64
- Desktop Environment: sway
- How did you install Mirage? Locally built via [AUR package](https://aur.archlinux.org/packages/matrix-mirage-git)
- For manual installations: Qt 5.15.2
- For manual installations: Python 3.9.3

### Steps to reproduce

1. Send the above URL with Mirage to someone else (or to yourself in a room with only you in it)
2. Note that the full URL is clickable and points to the correct destination
3. Send the above URL from another client (tested with Element and FluffyChat) and view the message with Mirage
4. Note that the clickable part stops at the colon, and the remainder is also missing from the link's destination

### Expected behavior

The full URL should be clickable and linked

### Actual behavior

The clickable part as well as the link's destination are truncated at colon characters (`:`)

**Comment by MRAAGH** [comment]
Fixed in 91652f9b89bc2f71bca0896028674a8aa221b238
