### ISSUE TITLE
problems with non-ascii characters in message

### ISSUE THREAD

**Issue by 3nt3** [mirukana/mirage#222]
### Description

When adding a non-ascii character to a message (in my case "ü"), the client throws the following error message:

```
'ascii' codec can't encode character '\xfc' in position 619: ordinal not in range(128)

Traceback (most recent call last):
  File "qrc:/src/backend/user_files.py", line 179, in _start_writer
    await new.write(self.serialized())
  File "/usr/lib/python3.9/site-packages/aiofiles/threadpool/utils.py", line 36, in method
    return (yield from self._loop.run_in_executor(self._executor, cb))
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 619: ordinal not in range(128)
```

### Your environment

- OS or distribution: Arch Linux
- Architecture: x86 64bit
- For Linux users: your desktop environment or window manager: bspwm 0.9.10
- How did you install Mirage? arch repository

### Steps to reproduce

1. add "ü" to a message (or any other non-ascii character)
2. error

### Expected behavior

Not throw an error

### Actual behavior

Throws an error

**Comment by mirukana** [comment]
Can you try the scripts in https://github.com/mirukana/mirage/issues/170, and post the outputs there?
