### ISSUE TITLE
please add this feature (proxies)

### ISSUE THREAD

**Issue by Joe257213** [mirukana/mirage#226]
i think mirage is a very great matrix client and it has missing only 1 thing for me to use it which is proxies so please add proxies so  i can run it with tor.

**Comment by bbhtt** [comment]
What version are you on? https://github.com/mirukana/mirage/releases/tag/v0.7.0 says SOCKS5 proxy is available.

https://github.com/mirukana/mirage/blob/master/src/config/settings.py#L36-L40

**Comment by Joe257213** [comment]
ok thank s am sorry
