### ISSUE TITLE
Can't enter # on MacOS

### ISSUE THREAD

**Issue by ara4n** [mirukana/mirage#23]
I just built on macOS - INSTALL.md pretty much worked without needing any changes :)

However, i can't enter # in the app (e.g. to join a room) because # on macOS on a UK keyboard is alt+3 - which instead switches to the third tab in the room list.  It'd probably be more idiomatic on macOS to use cmd-+3 for this (e.g. switching tabs in Chrome is cmd+number).

**Comment by mirukana** [comment]
I can change the default shortcuts if the app detects it runs on mac. Are there any other (full list in `settings.json`) that cause issues?

**Comment by mirukana** [comment]
Alt+number keybinds fixed in [v0.4.3](https://github.com/mirukana/mirage/releases/tag/v0.4.3), closing for now
