### ISSUE TITLE
Really long loading time on startup

### ISSUE THREAD

**Issue by toger5** [mirukana/mirage#25]
I have a account with about 100 rooms. (which is definitly not too much)
And the startup time is really long. It definitly loads longer than one minute.

**Comment by mirukana** [comment]
This is currently being worked on in the [performance branch](https://github.com/mirukana/mirage/tree/performance). In the next release, for large accounts, initial syncs will be much faster and ram usage will be a lot lower.

**Comment by mirukana** [comment]
Loading should be much faster in the 0.5.0 release, although we still need to do initial syncs on every startup until support for client state persistence in nio is implemented.

**Comment by toger5** [comment]
Yea it is great now! at least you can see the chats poping up and get feedback that sth is happening!
