### ISSUE TITLE
0.7.2 unusable in phone, scrolling doesn't work

### ISSUE THREAD

**Issue by sc0w** [mirukana/mirage#264]
### Description

I can't go forward / back with finger to go main chats / inside chat / list of members of chats

I can't go up / down with finger if the list of chats aren't in all the window

### Your environment

- mobian pinephone
- everything was working with mirage 0.6.4

### Steps to reproduce

1. install mirage 0.7.2
2. try to use it

### Expected behavior

everything must work

### Actual behavior

it is unusable

**Comment by sc0w** [comment]
I tried with `kinetic: bool = False` and `True` in `settings.py` but the same happens

**Comment by Newbytee** [comment]
Duplicate of https://github.com/mirukana/mirage/issues/236 I think

**Comment by sc0w** [comment]
yes, thanks
