### ISSUE TITLE
Uploads with Transfer-Encoding: chunked do not work with Synapse

### ISSUE THREAD

**Issue by DataBeaver** [mirukana/mirage#37]
I tried to upload a profile picture and got a 500 response from the server.  Synapse's log complains about missing Content-Length header.  This is arguably a bug with Synapse, but given that it was reported there a year ago and still hasn't been fixed, would it be possible to make Mirage send uploads using content length instead of chunked transfer encoding?

**Comment by mirukana** [comment]
This was already fixed in the dev branch after taking care of https://github.com/poljar/matrix-nio/issues/116, I added it to master as well.
