### ISSUE TITLE
Poor utilization of wide screens

### ISSUE THREAD

**Issue by DataBeaver** [mirukana/mirage#41]
It looks like messages have a max width of about 585 pixels (37.5 times the font size, looking at the source).  This means that if I maximize the Mirage window on my 1440p screen, only about one third of the width available for messages is utilized.  I know it gets difficult to follow lines if they are too long, but I think on desktop systems users should be able to decide what they're comfortable with by adjusting the window width.

**Comment by mirukana** [comment]
I added a setting to control the max message width in the dev branch: https://github.com/mirukana/mirage/commit/60ad7416d93cd27fc0f9d5a4870746879b601984.
It won't be infinite by default, I assume most people will expect the text to be readable without having to manually fiddle with their window's size, and 50-70 characters per line is the accepted common value according to UX studies and general opinion.
