### ISSUE TITLE
Launching with non-empty room filter duplicates account in left pane

### ISSUE THREAD

**Issue by ProgrammerPolymathic** [mirukana/mirage#45]
If Mirage 0.5.0 is launched with a single account, something is written in the room filter, and then Mirage is closed and launched again, a ghost account seems to be created, which is stuck in a continuous loading state.  Clearing the filter and restarting Mirage fixes the problem.

This issue was not present in the 0.4.3 release.  I don't have more than one account to test what happens if more than one is logged in.

Below is a screenshot of the issue, where the account in the loading state is a duplicate of the first account (apologies if the "sanitation" impedes understanding of the image; I speak with some people that would take issue with any names or messages being shared publicly).

![MirageAccountDuplicationSanitized](https://user-images.githubusercontent.com/65666545/82734092-722a3000-9ce6-11ea-91c7-446f8f34e63c.png)

**Comment by mirukana** [comment]
Something is wrong in the python code that handles filtering data, I've stumbled on some other cases where this happens. Will try to fix for 0.5.1.

**Comment by mirukana** [comment]
Can you check if the issue is still present on the dev branch at commit https://github.com/mirukana/mirage/commit/6ccf8dba64d67eb4300845bdb1ade671113f306f?

**Comment by ProgrammerPolymathic** [comment]
I've checked; the issue is gone in that commit.
