### ISSUE TITLE
Grouping favorites, direct chats and group chats

### ISSUE THREAD

**Issue by IngwiePhoenix** [mirukana/mirage#47]
I am in a lot of groups but also use Matrix as a do-it-all messenger for WhatsApp, Facebook and Telegram. In Riot, I often take advantage of classifying something as a "direct chat", while pinning a few chats as my absolute favorites (gotta find my mom fast to reply, or she'll be mad... :P )

I am a bit overrun right now with just how many things popped up in the sidebar and i have to find some way of organizing that now. Oof.

**Comment by mirukana** [comment]
See #6
