### ISSUE TITLE
Unpredictable scrollbar size

### ISSUE THREAD

**Issue by travankor** [mirukana/mirage#58]
### Description

The scrollbar length is quite unpredictable at times and is sometimes so small that you can't use it effectively. This seems to happen when you resize the window vertically.

### Your environment

- Void Linux 
- x86 64bit
- How did you install Mirage? Distro

### Steps to reproduce

1. Use a tiling window manager (since windows resize a lot).
2. Tile new window(s) vertically.
3. Notice the scrollbar is in an awkward location at the bottom of the screen and is small.
4. Delete vertical windows.
5. Scrollbar isn't original size.

### Expected behavior

The scrollbar should probably become smaller when the vertical size of the window decreases, but not to such an extreme. Also, the scrollbar should return to its original vertical size if the main window returns to its original size.

### Actual behavior

The scrollbar is small and unuseable.

**Comment by mirukana** [comment]
I added a minimum bar height of 48px in https://github.com/mirukana/mirage/commit/e756bd2909c4a22adf466800634f1dfe3554cb33.

What window manager are you using? The bars aren't in awkward locations and go back to their sizes normally for me on bspwm.

**Comment by travankor** [comment]
I'm using Sway, so perhaps Wayland+QT+QML is doing something. It seems like the weird positioning was a combination of the window resizing and the scrollback buffer increasing (causing the scrollbar to shrink) as it loaded.

Also could you remove the padding from the scrollbar, so that it's easier to just click to a specific location? Alternatively, you could make the detection area wider.

**Comment by mirukana** [comment]
![20200622_141427-maim](https://user-images.githubusercontent.com/34984680/85321637-fbbe5080-b492-11ea-8f39-4e9760fc11b4.png)
The scrollbars have been overhauled in the latest dev branch commits: no more padding, now visible without squinting, match the app's look and customizable via [theme](https://github.com/mirukana/mirage/commit/783a711799a0576dd82eede465aca93202ba90b4#diff-b5a0516daab0642a8d67420e78901b56).
