### ISSUE TITLE
Can't Figure Out how to add new account

### ISSUE THREAD

**Issue by colemickens** [mirukana/mirage#59]
### Description

I'm packaging this for nixpkgs for NixOS users. I'm a bit stuck, how do I add a second account?

I tried manually adding it to the config file and was able to make some progress and once got the "add account screen" to popup, but ... I feel like I'm missing a button somewhere?

**Comment by colemickens** [comment]
And then I alt-tab to look at the config file and I see the keybindings.

All the same, it seems like a button would be useful.

**Comment by mirukana** [comment]
![20200621_065836-maim](https://user-images.githubusercontent.com/34984680/85222925-b44d9c80-b38c-11ea-9de6-6f41cb44bc25.png)
Key button on the bottom left
