### ISSUE TITLE
Matrix Room for Discussion?

### ISSUE THREAD

**Issue by colemickens** [mirukana/mirage#60]
### Description

Hi. Is there a matrix room somewhere for discussion of Mirage?

Thanks for Mirage btw, I'm cleaning up the package definition for nixpkgs, but it's working well. Exciting to have more Matrix clients!

**Comment by mirukana** [comment]
[#mirage-client:matrix.org](https://matrix.to/#/#mirage-client:matrix.org)
There's a link to it just under the [README's title](https://matrix.to/#/#mirage-client:matrix.org).

Thanks for working on the nix package! Let me know if there's a related issue/thread I can follow, or if it's already published.
