### ISSUE TITLE
Command for opening files

### ISSUE THREAD

**Issue by BurnyBoi** [mirukana/mirage#62]
When looking at a file upload in Mirage, it seems like the only way to open a file currently is by clicking on it. In order to allow keyboard control for this same action, a command should be added. One could re-use `openMessagesLinks` to do double duty (since uploads are links any way), or have a different command for opening.

**Comment by mirukana** [comment]
Added to the dev branch (note that the keybind has been renamed to `openMessagesLinksOrFiles`)
