### ISSUE TITLE
Logging in to an existing account replaces current session

### ISSUE THREAD

**Issue by vSLG** [mirukana/mirage#63]
### Description

Logging in to an existing account in mirage leads to new session creation, replacing current session for account and forever losing the room keys.

### Environment

- OS: Void Linux, kernel 5.6.14_1
- Architecture: x86_64
- Window manager: i3wm 
- Qt version: 5.15.0
- Python version: 3.8.3
- Mirage built manually

### Steps to reproduce

1. Log in to an account
2. Send some messages in a room
3. Log in to the same account again
4. Check the same room again and all the messages will be undecryptable

### Expected behavior

- Fail to log in; or
- Warn about adding an existing account; or
- Redirect to account settings page.

### Actual behavior

Account gets added flawlessly and forgets about old session.

**Comment by mirukana** [comment]
Fixed by https://github.com/mirukana/mirage/pull/80
