### ISSUE TITLE
mxids with dashes are not detected properly 

### ISSUE THREAD

**Issue by ellietheoracle** [mirukana/mirage#64]
### Description

mxids, such as @theotheroracle:the-apothecary.club are only detected as @theotheroracle:the

![Screenshot from 2020-06-27 04-21-36](https://user-images.githubusercontent.com/20211219/85919074-cec0c380-b82d-11ea-952a-84dc4b13dd94.png)

### Expected behavior

the entire mxid should be detected

### Actual behavior

it's only detected up to the point at wich the dash is

**Comment by mirukana** [comment]
Fixed in https://github.com/mirukana/mirage/commit/b9f5ec4b72b2eafb729f903a10d8ea915c77ca12
