### ISSUE TITLE
adjust kinetic scrolling speed 

### ISSUE THREAD

**Issue by ellietheoracle** [mirukana/mirage#65]
i have a touchpad and scrolling with kinetics on is nearly unusable, but it's sort of annoying not to have it, would be nice if the speed was adjustable

**Comment by mirukana** [comment]
Added an option for this in https://github.com/mirukana/mirage/commit/f3d0b93583c9ac0d9667ac85b090d03d28a40799, the default is now a more conservative 2500 instead of 4000 like before.
