### ISSUE TITLE
changing environment variables

### ISSUE THREAD

**Issue by pp0-0051** [mirukana/mirage#77]
@mirukana
How can the following environment variables be changed?
Can it be done through settings.json file?

MIRAGE_CONFIG_DIR
MIRAGE_DATA_DIR
MIRAGE_CACHE_DIR

**Comment by mirukana** [comment]
These are set in your terminal before running the program inside it, example:
```sh
export MIRAGE_CONFIG_DIR=~/some-folder
export MIRAGE_DATA_DIR=~/some-other-folder
mirage
```
You can add the `export` lines to `/etc/profile` to affect Mirage without having to type them manually in a terminal every time (logout from your desktop and login again for it to take effect).

You can also override env variables directly when you run a command, using the syntax `VARIABLE=value command`, e.g. `MIRAGE_CONFIG_DIR=~/some-folder MIRAGE_DATA_DIR=~/some-other-folder mirage`.
