### ISSUE TITLE
Right pane frequently is shown as an overlay on mobile

### ISSUE THREAD

**Issue by rinigus** [mirukana/mirage#8]
When using Mirage in a narrow mode (only one pane visible, as on mobile), the right pane is frequently shown as an overlay on the top of the main pane. 

To reproduce:

1. resize to narrow mode
2. change selection of a room in rooms overview
3. in text messages pane, switch to the right one.

As a result, the right pane will be rendered on top of the main one. If you resize the window to wide mode and back to the narrow one, all will work as it should.

![screenshot](https://user-images.githubusercontent.com/15706605/77429715-baaa9780-6de2-11ea-9cbd-6e5f0a190c04.png)

**Comment by theotheroracle** [comment]
another note, if you close the side panel, and re-open it, it also functions properly .

**Comment by mirukana** [comment]
This shouldn't happen anymore in the dev branch, can you confirm?

**Comment by theotheroracle** [comment]
yeah it's fixed

**Comment by rinigus** [comment]
That looks to be fixed. Closing
