### ISSUE TITLE
Reply with an <img> 

### ISSUE THREAD

**Issue by theotheroracle** [mirukana/mirage#81]
you can't reply to a message with an m.image event, however, you can send an `<img>` tag in an m.message .

**Comment by mirukana** [comment]
You can use the markdown syntax for images in a reply (`![title](url)`), what is the issue?

**Comment by ellietheoracle** [comment]
oh, well that would work too, either way, the point is that it should be done automatically instead of saying "replying to messages with an image is not supported"

**Comment by mirukana** [comment]
Can you explain how that would work?
Also, consider we can't send encrypted images in an `<img>` tag.

**Comment by ellietheoracle** [comment]
it would need to upload the image to synapse, get the mxc url, and then generate the markdown or img tags automatically, could theoretically also be used to allow users to caption an image . i don't really know how to implement it in encrypted rooms, i don't think there's a way to do that in the spec yet .

**Comment by mirukana** [comment]
Implemented solution: https://github.com/mirukana/mirage/commit/0d2be820fec38e03a90b654829c9555d52836260 (see commit body)

It's less than ideal, but it works for all rooms including encrypted ones, and for any client that can display file events (support for inline images isn't common).
