### ISSUE TITLE
Change scrolling behaviour of room list

### ISSUE THREAD

**Issue by Cadair** [mirukana/mirage#85]
I am not sure what the best solution to this is, but I am finding myself repeatedly scrolling to the top of the room list to see which rooms have messages for me to read.

One possible mitigation would be to only scroll the room list down if the currently selected room goes out of view, rather than trying to centre it in the list. Alternatively, being able to disable the auto scroll so that the selected room can go out of view would be nice for me personally.

**Comment by mirukana** [comment]
Does https://github.com/mirukana/mirage/commit/d7d111705f8e8d703ccf923ab51f9d6f11f91866 solve your issue?

**Comment by mirukana** [comment]
Closing for lack of response, the original concern might be solved by the room list's behavior change in 0.7.0 too.
