### ISSUE TITLE
scrolling inverted on wayland

### ISSUE THREAD

**Issue by theotheroracle** [mirukana/mirage#86]
### Description

when scrolling ( i'm using a touchpad ) the direction is inverted
when switching to x11 fallback mode, the issue dissapears .

**Comment by mirukana** [comment]
Isn't this controlled by your desktop environment?

**Comment by ellietheoracle** [comment]
the issue doesn't happen in any other application ?

**Comment by colemickens** [comment]
I'm in Sway, I have `natural_scroll` enabled for my touchpad.

With my touchpad, scrolling is **correct** (aka, "natural" or "Australian" scrolling is properly working in Mirage).

With my external mouse, scrolling is **correct** (aka, normal. When I push my finger away from my body, "up" the wheel, the page scrolls up.)

So I can say that I'm not experiencing this issue.

**Comment by ellietheoracle** [comment]
it may be an issue with gnome ? i'll test it on sway in a bit .

**Comment by ellietheoracle** [comment]
another note, kinetic scrolling also doesn't work under wayland .

**Comment by travankor** [comment]
I have this issue on sway -- at least, firefox and mirage have opposite behavior with either value of  `natural_scrolling`. So, this would imply that one of them is wrong.

**Comment by theotheroracle** [comment]
the content should move in the direction of the scrolling

also, maybe this will be fixed when QT updates ? you mentioned that the title bar issue would be fixed when QT updates @mirukana so maybe they'll fix other wayland bugs as well ?

**Comment by mirukana** [comment]
Natural scrolling means the content moves down when you move your finger up and inversely. It should be the default behavior for a touch screen or trackpad. Do you not have this behavior? 

I tested GNOME 3.30 Wayland just now with a graphic tablet as way to scroll, the direction is what I expect (natural scrolling) and kinetic scrolling works perfectly.

**Comment by theotheroracle** [comment]
no, natural scrolling means that the content moves with your fingers, not the view .
![Screenshot from 2020-07-07 09-33-36](https://user-images.githubusercontent.com/20211219/86797159-f76a6980-c034-11ea-9a39-66fdecaf3851.png)

mirage is the only app that doesn't respect this behaviour . ( on wayland )

**Comment by travankor** [comment]
>Natural scrolling means the content moves down when you move your finger up and inversely. It should be the default behavior for a touch screen or trackpad. Do you not have this behavior?

Interesting, I have this behavior. So, I guess it works? However, I think it would be better if you respected the compositor's settings for natural scroll instead of (?) hardcoding the default (which is what other applications do).

**Comment by mirukana** [comment]
@theotheroracle: Wait, you didn't mention... did you enable or disable kinetic scrolling within Mirage? What about you @travankor ?

**Comment by travankor** [comment]
I have kinetic scrolling disabled, but I had the same behavior with kinetic scrolling enabled.

**Comment by travankor** [comment]
>I have this issue on sway -- at least, firefox and mirage have opposite behavior with either value of natural_scrolling. So, this would imply that one of them is wrong.

>Natural scrolling means the content moves down when you move your finger up and inversely. It should be the default behavior for a touch screen or trackpad. Do you not have this behavior?

I should clarify that my compositor (sway) has natural scrolling disabled and I observe natural scrolling in mirage. When I enable natural scrolling in my compositor, mirage no longer has natural scrolling.

**Comment by theotheroracle** [comment]
> @theotheroracle: Wait, you didn't mention... did you enable or disable kinetic scrolling within Mirage? What about you @travankor ?

wayland doesn't seem to support kinetic scrolling actually, the behaviour seems to be the same whether it is enabled or not .

**Comment by toger5** [comment]
The scrolling is also ridiculously slow compared to other wayland apps.

**Comment by maisiliymBridj** [comment]
Actually, what seems to be happening is that both events are sent (scroll up and scroll down), with one of them 'winning' over the other. This might be why @toger5 feels like it is scrolling slowly. This bug is quite awesome.

**Comment by theotheroracle** [comment]
I thought the behavior seemed the same wether kinetic scrolling was on or off on my system

**Comment by ronchaine** [comment]
Can confirm this bug, also with Sway.  Kinetic scrolling doesn't seem to do anything for me, and scrolling is inverse to every other program.

**Comment by MRAAGH** [comment]
@theotheroracle  completed? Did a dependency update fix this?

**Comment by theotheroracle** [comment]
as far as i know this issue is fixed by upstream, but also this repo is no longer active, so i didn't think my issues were needed here anymore
