### ISSUE TITLE
In room settings pane, left arrow does nothing when on settings

### ISSUE THREAD

**Issue by rinigus** [mirukana/mirage#9]
In narrow mode, when showing Settings of the room (see screenshot), the left arrow (top left) does not switch to the messages pane. In fact, its doing nothing in these conditions.

![screenshot](https://user-images.githubusercontent.com/15706605/77429931-1412c680-6de3-11ea-8eb6-e81d545c215c.png)

**Comment by mirukana** [comment]
Fixed in https://github.com/mirukana/mirage/commit/75bbe48afe1a08f2296453696bb70d821a3f0704
