### ISSUE TITLE
request: hide right side bar

### ISSUE THREAD

**Issue by colemickens** [mirukana/mirage#93]
When the userlist is visible, clicking the "user icon" again should hide the user list. This allows the user to recover some space for the conversation view.

**Comment by mirukana** [comment]
You can reduce it to about 40px right now by dragging it or resizing the window, isn't that enough? It would be more practical to make clicking on the icon do that, especially since it's part of the list and would be gone if hidden.

**Comment by colemickens** [comment]
>You can reduce it to about 40px right now by dragging it or resizing the window, isn't that enough?

No. I don't like this trend of Fractal, etc trying to guess when to show hide sidebars based on the width of the window. It winds up never quite doing what I want or expect, interacts with my tiling WM weirdly, etc.

>It would be ore practical to make clicking on the icon do that, especially since it's part of the list and would be gone if hidden.

Hm. I think we mean the same thing. I meant re-clicking the "show user info" button in the top bar that remains visible.

**Comment by mirukana** [comment]
> Hm. I think we mean the same thing. I meant re-clicking the "show user info" button in the top bar that remains visible.

My idea is: when clicking the button, toggle between full size and minimum (~40px) size, is that what you meant too?

**Comment by colemickens** [comment]
Oh, no sorry, I still want to be able to hide it. :smile: For example, Riot vs Mirage. I feel like Mirage would win the density/comfort competition here if I could hide the side bars when I want to.

![mirage](https://user-images.githubusercontent.com/327028/86730414-5b644200-bfe3-11ea-91e1-0683ff443fdf.png)

**Comment by mirukana** [comment]
Added to dev branch, you can now click the current tab (e.g. user icon) or use the keybind (default Ctrl+Alt+R) to hide the room pane.

**Comment by colemickens** [comment]
I'm seeing this in the new release. Thanks!
