### ISSUE TITLE
mirage often doesn't exit properly

### ISSUE THREAD

**Issue by colemickens** [mirukana/mirage#95]
### Description

Mirage often fails to exit, and further, fails to respond to "ctrl-c" issue from the terminal where it's running.

Just now I had closed it, return to the workspace the terminal was on and noticed it was still humming along even though the UI was closed. (I don't have any tray that it would've been running it AFAIK).

### Your environment

- NixOS, x86_64-linux, Sway, Nix, qt 5.13, 3.8

### Steps to reproduce

1. Run it
2. Close the UI (I use sway to kill it)

### Expected behavior

The mirage process completely stops running.

### Actual behavior

It kept running.

**Comment by mirukana** [comment]
Fixed in 0.6.0
