### ISSUE TITLE
Display names with "<" 

### ISSUE THREAD

**Issue by theotheroracle** [mirukana/mirage#99]
### Description

When someone's name has "<"  in it, and they're mentioned, the entire message doesn't render . likely related to #83 but isn't the *same* bug, because the *entire message is missing* . the difference seems to be that the "<" tag isn't "closed" .

![Screenshot from 2020-07-05 10-28-17](https://user-images.githubusercontent.com/20211219/86536072-52bc2080-beaa-11ea-89ff-bae8af853773.png)
![Screenshot from 2020-07-05 10-28-28](https://user-images.githubusercontent.com/20211219/86536102-9747bc00-beaa-11ea-9779-cff40228d4a2.png)

**Comment by mirukana** [comment]
Fixed in dev branch.
